<a href="https://colab.research.google.com/github/CodeWithVu/pythonPrograming/blob/main/exercise/w4/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TUẦN 3: Numpy**

10 ví dụ numpy

1. Khởi tạo ma trận (list, hằng số, random).

2. Các phép toán cơ bản trên ma trận.

3. Thao tác hàng/cột.

4. Vector (mảng 1 chiều, cộng, dot, nhân ma trận với vector).

5. Mảng nhiều chiều (ndarray 3D).

6. Tách và ghép ma trận (hstack, vstack, slicing).

7. Một số hàm NumPy hữu ích (sum, mean, max, min, where, filter).

8. Số tuyến tính (định thức, nghịch đảo).

9. Ma trận chuyển vị & kiểm tra đối xứng.

10. Một số hàm NumPy mở rộng (search/research)

In [ ]:
import numpy as np


In [ ]:
# 1. Khởi tạo ma trận
# Cách 1: Từ hằng số hoặc list
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Ma trận A:\n", A)

# Ma trận toàn số 5 (hằng số)
C = np.full((3,3), 5)
print("\nMa trận toàn số 5:\n", C)

# Cách 2: Khởi tạo ngẫu nhiên
B = np.random.randint(0,10,(3,3))
print("\nMa trận B (random):\n", B)

Ma trận A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Ma trận toàn số 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

Ma trận B (random):
 [[2 1 3]
 [8 9 4]
 [1 3 6]]


In [ ]:
# 2. Các phép toán cơ bản trên ma trận
D = B + A
print("B + C =\n", D)

E = B - A
print("B - C =\n", E)

F = B * A
print("B * C =\n", F)

G = B / A
print("B / C =\n", G)
# Tích vô hướng
dot_AB = np.dot(A, B)
print("A · B =\n", dot_AB)

B + C =
 [[ 3  3  6]
 [12 14 10]
 [ 8 11 15]]
B - C =
 [[ 1 -1  0]
 [ 4  4 -2]
 [-6 -5 -3]]
B * C =
 [[ 2  2  9]
 [32 45 24]
 [ 7 24 54]]
B / C =
 [[2.         0.5        1.        ]
 [2.         1.8        0.66666667]
 [0.14285714 0.375      0.66666667]]
A · B =
 [[ 21  28  29]
 [ 54  67  68]
 [ 87 106 107]]


In [ ]:
# 3. Thao tác trên một hàng, một cột
# Lấy hàng 1, nhân 2
print(A[0, :] * 2)

# Lấy cột 2, cộng 10
print(A[:, 1] + 10)

# Thay cột 1 bằng toàn số 0
A[:, 0] = 0
print(A)

[198   4   6]
[12 15 18]
[[0 2 3]
 [0 5 6]
 [0 8 9]]


In [ ]:
# 4. Vector (mảng 1 chiều)
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("\nVector v1:", v1)
print("Vector v2:", v2)
print("Cộng vector:", v1+v2)
print("Tích vô hướng vector:", np.dot(v1,v2))

# Nhân ma trận với vector
print("A nhân v1:", np.dot(A, v1))


Vector v1: [1 2 3]
Vector v2: [4 5 6]
Cộng vector: [5 7 9]
Tích vô hướng vector: 32
A nhân v1: [13 28 43]


In [ ]:
# 5. Thao tác trên mảng hai chiều
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Lấy một phần tử
print(A[0, 1])     # hàng 0, cột 1 → 2

# Lấy một hàng
print(A[1, :])     # hàng thứ 2 → [4 5 6]

# Lấy một cột
print(A[:, 2])     # cột thứ 3 → [3 6 9]

# Cắt sub-ma trận
print(A[0:2, 1:3]) # lấy 2 hàng đầu, cột 1-2 → [[2 3] [5 6]]

# Thay đổi giá trị
A[0, 0] = 99
print(A)

2
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
# 6. Tách và ghép ma trận
# Ghép ma trận
V = np.vstack((A, B))
print("Ghép dọc:\n", V)

# Ghép theo cột (ngang - horizontal)
H = np.hstack((A, B))
print("Ghép ngang:\n", H)

# Ghép tổng quát (axis=0: theo hàng, axis=1: theo cột)
J = np.concatenate((A, B), axis=0)  # ghép dọc
print("concatenate axis=0:\n", J)

L = np.concatenate((A, B), axis=1)  # ghép ngang
print("concatenate axis=1:\n", L)

Ghép dọc:
 [[0 2 3]
 [0 5 6]
 [0 8 9]
 [2 1 3]
 [8 9 4]
 [1 3 6]]
Ghép ngang:
 [[0 2 3 2 1 3]
 [0 5 6 8 9 4]
 [0 8 9 1 3 6]]
concatenate axis=0:
 [[0 2 3]
 [0 5 6]
 [0 8 9]
 [2 1 3]
 [8 9 4]
 [1 3 6]]
concatenate axis=1:
 [[0 2 3 2 1 3]
 [0 5 6 8 9 4]
 [0 8 9 1 3 6]]


In [ ]:
# Tách ma trận
# Tách theo cột
cols = np.hsplit(B, 3)   # tách thành 2 ma trận con theo cột
print("Tách cột:", cols)

# Tách theo hàng
rows = np.vsplit(B, 3)   # tách thành 2 ma trận con theo hàng
print("Tách hàng:", rows)

# Tách vector 1D
v = np.array([10, 20, 30, 40, 50])
parts = np.split(v, [2, 4])  # tách tại vị trí index 2 và 4
print("Tách vector:", parts)

Tách cột: [array([[2],
       [8],
       [1]]), array([[1],
       [9],
       [3]]), array([[3],
       [4],
       [6]])]
Tách hàng: [array([[2, 1, 3]]), array([[8, 9, 4]]), array([[1, 3, 6]])]
Tách vector: [array([10, 20]), array([30, 40]), array([50])]


In [ ]:
# 7. Một số hàm NumPy hữu ích
data = np.array([10,20,30,40,50])
print("\nTổng:", np.sum(data))
print("Trung bình:", np.mean(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Vị trí của 30:", np.where(data==30))
print("Các số > 25:", data[data>25])


Tổng: 150
Trung bình: 30.0
Max: 50
Min: 10
Vị trí của 30: (array([2]),)
Các số > 25: [30 40 50]


In [ ]:
# 8. Đại số tuyến tính
M = np.array([[1,2],[3,4]])
print("\nĐịnh thức của M:", np.linalg.det(M))
print("Nghịch đảo của M:\n", np.linalg.inv(M))


Định thức của M: -2.0000000000000004
Nghịch đảo của M:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# 9. Ma trận chuyển vị & ma trận đối xứng
print("\nMa trận A chuyển vị:\n", A.T)   # transpose
print("Kiểm tra A có đối xứng không?:", np.allclose(A, A.T))



Ma trận A chuyển vị:
 [[0 0 0]
 [2 5 8]
 [3 6 9]]
Kiểm tra A có đối xứng không?: False


In [ ]:
#10. Một số hàm NumPy mở rộng (search/research)
G = np.array([1, 2, 3, 4, 5])
print("Trung bình =", np.mean(G))
print("Độ lệch chuẩn =", np.std(G))
print("Tích luỹ (cumsum) =", np.cumsum(G))
print("Sắp xếp ngược =", np.sort(G)[::-1])

Trung bình = 3.0
Độ lệch chuẩn = 1.4142135623730951
Tích luỹ (cumsum) = [ 1  3  6 10 15]
Sắp xếp ngược = [5 4 3 2 1]
