In [2]:
import numpy as np


In [7]:
arr = np.random.rand(5, 5)

arr2 = np.random.randint(0, 10, (5,5))

print(arr)

print(arr2)

[[0.99376427 0.19543443 0.75583016 0.36022652 0.19218305]
 [0.98317882 0.92685847 0.03032602 0.44428998 0.53900125]
 [0.74506764 0.34142037 0.71724883 0.12579072 0.17832398]
 [0.62050571 0.17409916 0.27017898 0.24091238 0.11809173]
 [0.54118774 0.13300076 0.97324664 0.05233582 0.87816965]]
[[7 2 8 4 6]
 [6 8 8 5 4]
 [0 1 3 7 9]
 [4 3 3 3 1]
 [8 0 0 5 2]]


In [9]:
# Nhân 2 ma trận
result1 = np.dot(arr, arr2)

# Chia 2 ma trận
result2 = np.divide(arr, arr2)

# Cộng 2 ma trận
result3 = np.add(arr, arr2)

# Trừ 2 ma trận
result4 = np.subtract(arr, arr2)
print(result1)
print(result2)
print(result3)
print(result4)

[[11.10732692  5.38751367 12.86175959 12.28463516 14.2913874 ]
 [18.53257245 10.74442139 16.70414633 12.80716597 11.40173347]
 [ 9.1937504   5.31611928 11.22102276 10.97710631 12.7737655 ]
 [ 7.29651829  3.62672078  7.89011301  6.5569673   7.32813758]
 [11.8210192   3.27663564  8.47025538 14.19033696 14.34702439]]
[[0.14196632 0.09771721 0.09447877 0.09005663 0.03203051]
 [0.16386314 0.11585731 0.00379075 0.088858   0.13475031]
 [       inf 0.34142037 0.23908294 0.0179701  0.01981378]
 [0.15512643 0.05803305 0.09005966 0.08030413 0.11809173]
 [0.06764847        inf        inf 0.01046716 0.43908482]]
[[7.99376427 2.19543443 8.75583016 4.36022652 6.19218305]
 [6.98317882 8.92685847 8.03032602 5.44428998 4.53900125]
 [0.74506764 1.34142037 3.71724883 7.12579072 9.17832398]
 [4.62050571 3.17409916 3.27017898 3.24091238 1.11809173]
 [8.54118774 0.13300076 0.97324664 5.05233582 2.87816965]]
[[-6.00623573 -1.80456557 -7.24416984 -3.63977348 -5.80781695]
 [-5.01682118 -7.07314153 -7.96967398 -

C:\temp\ipykernel_12324\746717382.py:5: RuntimeWarning: divide by zero encountered in divide
  result2 = np.divide(arr, arr2)



### Tách, ghép ma trận, vector

#### Ghép ma trận

In [30]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# ghép 2 ma trận với nhau thành 1 ma trận
join_arr_1D = np.concatenate((arr1, arr2))

# ghép 2 ma trận vói nhau thành ma trận 2 chiều
join_arr_2D = np.vstack((arr1, arr2))

join_arr_2D_stack = np.stack((arr1, arr2))

join_arr_2D_dstack = np.dstack((arr1, arr2))

print("ma trận 1-D sau khi ghép: ", join_arr_1D)
print("ma trận 2-D sau khi ghép: ", join_arr_2D)
print("ma trận 2-D sau khi stack: ", join_arr_2D_stack)
print("ma trận sau khi dstack: ", join_arr_2D_dstack)
print("---------------------")
print(join_arr_2D_dstack[0])

ma trận 1-D sau khi ghép:  [1 2 3 4 5 6]
ma trận 2-D sau khi ghép:  [[1 2 3]
 [4 5 6]]
ma trận 2-D sau khi stack:  [[1 2 3]
 [4 5 6]]
ma trận sau khi dstack:  [[[1 4]
  [2 5]
  [3 6]]]
---------------------
[[1 4]
 [2 5]
 [3 6]]


#### Tách ma trận

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5 6]
[7 8]


In [36]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### hàm shape, reshape, search, join

#### shape 

In [ ]:
# 

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


#### reshape